apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  DB_HOST: "infra-db.cexewma5pjqf.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_USER: "admin"
  DB_PASSWORD: "admin123"
  DB_NAME: "infra_db"
